"""Multi-agent state definitions for the LangGraph supervisor workflow."""

from __future__ import annotations

from typing import Annotated, Any, Dict, List, TypedDict

from langgraph.graph.message import add_messages
from langchain_core.messages import BaseMessage


class ExpertOutput(TypedDict, total=False):
    """Output produced by a single expert agent."""

    expert_name: str  # "summarizer" | "methodology" | "code_builder" | "literature" | "database_manager" | "writing_editor"
    content: str  # The expert's textual output
    metadata: Dict[str, Any]  # Extra structured data (e.g. {"paper_ids": [...], "error": "..."})


class AgentMemory(TypedDict, total=False):
    """Persistent memory snapshot loaded for one user/session."""

    session_id: str
    summary: str
    user_preferences: List[str]
    recent_topics: List[str]
    recent_paper_ids: List[str]
    active_skills: List[str]
    turn_count: int
    recent_code_project_path: str
    recent_code_project_slug: str
    recent_code_delivery_status: str
    recent_code_validation_evidence: str


def append_expert_outputs(
    existing: List[ExpertOutput] | None,
    updates: List[ExpertOutput] | None,
) -> List[ExpertOutput]:
    """LangGraph reducer that accumulates expert outputs across nodes."""
    return list(existing or []) + list(updates or [])


class MultiAgentState(TypedDict):
    """Shared state flowing through the multi-agent LangGraph.

    ``messages`` uses the ``add_messages`` reducer so that each node can
    append new messages without worrying about duplicates.
    """

    messages: Annotated[List[BaseMessage], add_messages]
    """Full conversation and tool-call history (accumulated)."""

    session_id: str
    """Stable client/session identifier used to load and persist memory."""

    memory: AgentMemory
    """Persistent memory snapshot available to supervisor and experts."""

    next_agent: str
    """Routing decision: ``"module_executor"`` or ``"FINISH"``. Set by the
    Supervisor, read by the conditional edge router."""

    expert_outputs: Annotated[List[ExpertOutput], append_expert_outputs]
    """Accumulated outputs from all experts that have run so far."""

    task_plan: List[str]
    """Ordered list of expert modules selected by the supervisor, e.g.
    ``["literature", "summarizer", "methodology"]``."""

    module_tasks: Dict[str, str]
    """Per-module task instructions generated by the supervisor planner."""

    current_task: str
    """Short description of the current sub-task (set by the Supervisor for
    downstream experts to consume)."""

    active_skills: List[str]
    """Names of skills that the supervisor has activated for this session.
    The supervisor presents available skills to the LLM; the LLM selects
    which to activate via the JSON ``skills`` field."""

    skill_overrides: Dict[str, dict]
    """Per-expert parameter overrides from activated skills, e.g.
    ``{"code_builder": {"language_hint": "matlab"}}``.  Experts read this
    to adjust their behavior dynamically."""

    code_workspace_path: str
    """Filesystem root where Code Builder creates project files. Code tools
    operate only under this directory and still require relative file paths."""

    code_workspace_is_project: bool
    """Whether ``code_workspace_path`` was explicitly selected as the project
    root instead of a parent workspace container."""

    code_python_executable: str
    """Python interpreter used by Code Builder Python, pytest, and shell
    commands for the current request."""
